{{ if .Values.htpasswd.enabled }}
apiVersion: v1
data:
  htpasswd: {{ .Values.htpasswd.htpasswd }}
kind: Secret
metadata:
  name: {{ template "oauth2-proxy.fullname" . }}-htpasswd
type: Opaque
{{- end -}}
